### ISSUE TITLE
curl: (22) The requested URL returned error: 403 Forbidden

### ISSUE THREAD

**Issue by santiagoperez96** [Accengage/ios-pod-specs#19]
Hey, i have problems installing Accengage-iOS-SDK-Extension.

Always i get 403 for this repository https://dl.bintray.com/accengage/iOS/AccengageKitExtension-1.1.0.zip

**Comment by SebKnopf** [comment]
Same here for https://dl.bintray.com/accengage/iOS/AccengageKit-6.4.4.zip

**Comment by Njko** [comment]
Same with the latest: https://dl.bintray.com/accengage/iOS/AccengageKit-7.1.1.zip :(

**Comment by megataps** [comment]
https://bintray.com/ has been sunset. :(

**Comment by omar-belhaouss** [comment]
Same here for https://dl.bintray.com/accengage/iOS/AccengageKit-7.0.3.zip 😢

**Comment by oristanovic** [comment]
@santiagoperez96 @Njko @omar-belhaouss @megataps @SebKnopf We're looking into it. The SDK versions will be available again asap.

**Comment by CameliaTripon** [comment]
@oristanovic 
Hello

I think we somehow the same issue 403 Forbidden when running pod install

[!] Error installing Accengage-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/vb/628zbf_924z_2jtx1fmy8rk80000gn/T/d20210520-90232-101jdfk/file.zip https://dl.bintray.com/accengage/iOS/AccengageKit-6.4.1.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (22) The requested URL returned error: 403 Forbidden


PLEASE fix it soon as it block our release and development

**Comment by aliabbas90** [comment]
Hello @CameliaTripon, I am not a part of the team, but I will try to help you.
You are using the old URL source to download the Accengage SDK (dl. binary). To fix this, run a `pod repo update` to update the `podspec` file and retry with a `pod install`

Also, update to version 6.4.4 as the forbidden links have been updated for `6.4.4` and above and not for the `6.4.1`.

**Comment by Njko** [comment]
Hi Camelia,

The podspec has been recently updated. Try running « pod repo update »
before running « pod install ». If the url of the podspecs still targets
bintray, they are obsolete.

Hope this helps.

Le ven. 21 mai 2021 à 09:35, Camelia Tripon ***@***.***> a
écrit :

**Comment by CameliaTripon** [comment]
Is working with 6.4.4. Thanks.
