### ISSUE TITLE
Cocoapods warning

### ISSUE THREAD

**Issue by jpierceMLD** [Accengage/ios-pod-specs#2]
When adding Accengage-iOS-SDK-Extension (v1.1.0), cocoapods issues the following warning:

`[!] 'Accengage-iOS-SDK-Extension' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts in there. Please reach out to the library author to notify them of this security issue.`

**Comment by oristanovic** [comment]
Fixed. You shouldn't see the warning anymore.
