### ISSUE TITLE
Empty Pod

### ISSUE THREAD

**Issue by tukestolo** [Accengage/ios-pod-specs#20]
When I try to use it, we receive a ok installation but on pod we only have support files and cannot import or use it.

![image](https://user-images.githubusercontent.com/61240309/117163859-f8d30280-adbb-11eb-971e-62e7626e654c.png)

![image](https://user-images.githubusercontent.com/61240309/117163818-f1135e00-adbb-11eb-9180-580cfe3d86c1.png)

**Comment by tukestolo** [comment]
@oristanovic @yacir

**Comment by oristanovic** [comment]
@pedrooliveiraJumia Probably related to https://github.com/urbanairship/ios-pod-specs/issues/19, could you clear the cache and retry?

**Comment by tukestolo** [comment]
@oristanovic i have tried already

![image](https://user-images.githubusercontent.com/61240309/119347932-1943fd80-bc94-11eb-8334-26330c0708cb.png)


but always same result

![image](https://user-images.githubusercontent.com/61240309/119347967-25c85600-bc94-11eb-8986-d7b58396b209.png)

**Comment by oristanovic** [comment]
Could you check if this solves it for you: 
`rm -rf ~/Library/Caches/CocoaPods` 
`rm -rf Pods`
`rm -rf ~/Library/Developer/Xcode/DerivedData/*`
`pod deintegrate`
`pod setup`
`pod install`

**Comment by tukestolo** [comment]
it works !! 
thanks.
