### ISSUE TITLE
Cocoapods error installing Accengage-iOS-SDK

### ISSUE THREAD

**Issue by CameliaTripon** [Accengage/ios-pod-specs#21]
Hello. We get this error when running pod install for Accengage.

[!] Error installing Accengage-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/vb/628zbf_924z_2jtx1fmy8rk80000gn/T/d20210520-90232-101jdfk/file.zip https://dl.bintray.com/accengage/iOS/AccengageKit-6.4.1.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden

Please fix it soon. We need it for a release

**Comment by oristanovic** [comment]
The version 6.4.1 is obsolete since it contains UIWebView and therefore you wouldn’t be able to publish to App Store. Please update to 6.4.5.

**Comment by CameliaTripon** [comment]
is working now. Thanks
