### ISSUE TITLE
Podspecs use insecure HTTP urls for downloads

### ISSUE THREAD

**Issue by nikolaykasyanov** [Accengage/ios-pod-specs#4]
https://krausefx.com/blog/trusting-sdks

https://github.com/Accengage/ios-pod-specs/blob/9f3a9e1f63bdd641e1b0898dddef48766435cc3c/Accengage-iOS-SDK/6.1.5/Accengage-iOS-SDK.podspec#L21

**Comment by oristanovic** [comment]
Fixed in the latest SDK release.
