### ISSUE TITLE
Can't install SDK with CocoaPods

### ISSUE THREAD

**Issue by jbrunhuber** [Accengage/ios-pod-specs#6]
We can't install the Accengage-SDK using CocoaPods. Seems like there are Problems with the SSL configuration on the accengage server.

**Steps to reproduce:**
* Delete all CocoaPods caches
* Run `pod install`

**Error output:**
```
Analyzing dependencies
Downloading dependencies
Installing Accengage-iOS-SDK (6.2.1)

[!] Error installing Accengage-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/1g/srbzk5ks4_q05l6bwfn23vn00000gn/T/d20190416-6418-zwkog2/file.zip https://docs.accengage.com/sdk/ios/AccengageKit-6.2.1.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to docs.accengage.com:443
```

**Comment by LoicGombeaud** [comment]
Same here, and it's blocking our delivery process

**Comment by LoicGombeaud** [comment]
@jbrunhuber The issue seems to be solved

**Comment by jbrunhuber** [comment]
Still getting the SSL Error 😕 I'll try deleting all caches later and try it again.

**Comment by oristanovic** [comment]
Hi @jbrunhuber,
Sorry about this, there was a temporary issue with our server causing this error but it should be fine now. Let us know if the problem persists on your side.
