### ISSUE TITLE
Checksum error in cocoapod

### ISSUE THREAD

**Issue by denisPoifol** [Accengage/ios-pod-specs#7]
Since your last update the 7th of may, I am getting an error on my CI system :
The podfile.lock contains changes
```
12:03:52  SPEC CHECKSUMS:
12:03:52 -  Accengage-iOS-SDK: 984688556c22c1b86bfd924963421bd22824743b
12:03:52 +  Accengage-iOS-SDK: 3ca71d11770e9a97be0bc24da9bc3b6f57d92f52
```
looking at it a bit closer I realised even though I was asking for the 6.1 version in my podfile 
`pod 'Accengage-iOS-SDK', '~> 6.1'`
The installed version in the podfile.lock was 6.3
`- Accengage-iOS-SDK (6.3.2)`
So I thought I could fix my issue by upgrading to the latest version 6.4 but even when asking :
`pod 'Accengage-iOS-SDK', '~> 6.4'` and thus installing
`- Accengage-iOS-SDK (6.4.2)``
I find myself with the same issue where the check sum changed in the podfile.lock while installing it on my CI :
```10:57:20  SPEC CHECKSUMS:
10:57:20 -  Accengage-iOS-SDK: cbc7783c79dc5b5094b62cf48f4dafaaabad83c5
10:57:20 +  Accengage-iOS-SDK: ae61bfd76709089ec76dde8266a0d75906b2a45e```

**Comment by oristanovic** [comment]
@denisPoifol 

The last update we made concerns only newer podspec files (6.2 and later) so not really sure if it's related to your issue.

Could you try removing the pods and podfile.lock and running install again ?

**Comment by denisPoifol** [comment]
Already tried that. I end up with the same result.
I finaly found a way to resolve my CI issue by updating CocoaPods to `1.7.0.RC.2` and running `bundle exec pod repo update && bundle exec pod install` instead of `bundle exec pod install --repo-update`
Like suggested here : https://github.com/CocoaPods/CocoaPods/issues/8421
But I still end up with 6.3 being installed when  specifying  6.1 in my Podfile. This is a non issue for me but it clues that something is wrong in the way you are publishing versions.

**Comment by oristanovic** [comment]
I believe that what you're seeing is the behaviour of the optimistic operator ~>
Could you try `pod 'Accengage-iOS-SDK', '6.1'` instead of `pod 'Accengage-iOS-SDK', '~> 6.1'`

**Comment by denisPoifol** [comment]
Indeed my mistake.
